Fix the issue that NoClassDefFoundError when access various query pages
A possible reason is that in constructor of these pages, ANTLR based
query is parsed and this can cause JDK bugs. Now the logic is moved in
to a LoadableDetachableModel